namespace CA23101302
{
    internal class Program
    {
        static void Main()
        {
            List<Dog> dogs = GetDogsFromFile("dogs [Generated by OpenAI].txt");
            //DogListTest(dogs);
        }

        private static List<Dog> GetDogsFromFile(string filename)
        {
            List<Dog> list = new();
            using StreamReader streamReader = new($@"..\..\..\src\{filename}");
            _ = streamReader.ReadLine();
            while (!streamReader.EndOfStream) list.Add(new(streamReader.ReadLine()));
            return list;
        }
        private static void DogListTest(List<Dog> list)
        {
            Console.Write("Number of elements in the list: ");
            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine(list.Count);

            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("\nBreed Name;");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("Average Weight (lbs);");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("Average Height (inches);");
            Console.ForegroundColor = ConsoleColor.Magenta;
            Console.Write("Temperament;");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write("Lifespan (years);");
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine("Origin\n");

            foreach (var dog in list)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.Write($"{dog.Name};");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write($"{dog.Weight};");
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.Write($"{dog.Height:0.0};");
                Console.ForegroundColor = ConsoleColor.Magenta;
                string tmpstr = "";
                foreach (var tem in dog.Temperament) tmpstr += $"{tem}, ";
                tmpstr = tmpstr[..^2];
                Console.Write($"[{tmpstr}];");
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.Write($"{dog.Lifespan.AvgMin}-{dog.Lifespan.AvgMax};");
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine($"{dog.Origin}");
            }

            Console.ResetColor();
        }
    }
}